name: 'Try Build'

on: push

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-18.04.5
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 1.8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Checkout submodules'
        uses: textbook/git-checkout-submodule-action@master
      - name: 'Install 32-bit dependencies'
        run: sudo apt-get install -y libc6-i386 lib32z1 lib32stdc++6
      - name: 'Fetch Source'
        run: git fetch origin master
      - name: 'Checkout Master'
        run: git checkout master
      - name: 'Merge Source'
        run: git merge master origin/master
      - name: 'Make Auth Key'
        run: ant MakeAuthKey
        working-directory: appinventor
      - name: 'Clean Build'
        run: ant clean
        working-directory: appinventor
      - name: 'Build AppInventor'
        run: ant noplay
        working-directory: appinventor
      - name: 'Build Companion'
        run: ant
        working-directory: appinventor
      - name: 'Upload Companion to Artifacts'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: MIT AI2 Companion
          path: appinventor/build/buildserver/MIT AI2 Companion.apk
      - name: 'Upload Companion Full to Artifacts'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: MIT AI2 Companion Full
          path: appinventor/build/buildserver/MITAI2Companion-full.apk
      - name: 'Run Tests'
        run: ant tests
        working-directory: appinventor
      - name: 'Upload Test Reports to Artifacts'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Test Reports
          path: appinventor/reports
      - name: 'Pack War'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: PackWar
          path: appinventor/appengine/build/war
      - name: 'BuildServer Tar'
        run: ant BuildDeploymentTar
        working-directory: appinventor/buildserver
      - name: 'Pack BuildServer'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BuildServerTar
          path: appinventor/build/buildserver/BuildServer.tar
